### ISSUE TITLE
Empty Flexible content

### ISSUE THREAD

**Issue by Senexis** [whitecube/nova-flexible-content#475]
Currently, when viewing pages, the flexible content is empty.

## Details
It seems to be caused by the recent changes for compatiblity with Nova 4.26, but I never had any issues in the first place with it, and now that a call to `is_a()` is replaced from `\stdClass` to `Fluent`, the detection for `\stdClass` instances is broken.

I don't quite know how or why I don't experience issues in Nova 4.26 with version <1.0.9, but I don't. My layouts still are instances of `\stdClass`, so removing the check from `getMappedLayout` in `HasFlexible` seems to break my installation (`getMappedLayout` returns `null`). Reverting back to version 1.0.8 fixes the issue and is fully compatible with my usecase in Nova 4.26.

For posterity and sake of completeness:
- The output of `get_class` and `class_parents` are `stdClass` and `[]` respectively.
- I am using `protected $casts = ['content' => FlexibleCast::class]` to cast the content.
- This happens in both existing, newly seeded, and newly created pages.
- I am using custom Layout classes, normally extending the `Whitecube\NovaFlexibleContent\Layouts\Layout` class, and only having the required fields.
- Layout classes are registered using `->addLayout([Layout]::class)`.
- I am editing a regular resource, not a custom tool like `outl1ne/nova-settings`.

## Proposed fix
The recent commits removed the check for `is_a($item, \stdClass)` (`HasFlexible.php:125` in 1.0.8). This should be added back in the same elseif as `Fluent::class`, probably (ex. `elseif (is_a($item, Fluent::class) || is_a($item, \stdClass::class))`). I am not sure (and not feasibly able to test) whether this breaks things for people that are experiencing issues with >=1.0.9 and 4.26, hence I am not able to comfortably Pull Request.

**Comment by PieterCappelle** [comment]
Agree, having same issues. Laravel Nova 4.26 and latest version of this module. This breaks the entire module. `content` is empty after this change.

https://github.com/whitecube/nova-flexible-content/pull/469

**Comment by mabdullahsari** [comment]
This has been fixed with #474. A patch release has to be tagged now.

**Comment by Jaspur** [comment]
@mabdullahsari that did not fix it. I upgraded from v1.0.8: `Upgrading whitecube/nova-flexible-content (v1.0.8 => v1.0.11)`

When using v1.0.8 (and ` "laravel/nova": "4.25.1",`):
<img width="439" alt="Scherm­afbeelding 2023-07-11 om 09 10 43" src="https://github.com/whitecube/nova-flexible-content/assets/4254854/c86d0cd5-ba3a-438e-a42e-4da5f556b299">

When using v1.0.11 (and ` "laravel/nova": "4.26.4",):
<img width="435" alt="Scherm­afbeelding 2023-07-11 om 09 10 06" src="https://github.com/whitecube/nova-flexible-content/assets/4254854/456ff2fa-3090-4460-9d98-726b4409f1a2">

**Comment by Senexis** [comment]
@Jaspur It doesn't have a release het. For now, you should be able to use dev-master as the composer version to get the changes.

**Comment by RiccardoRomoliU2Y** [comment]
@Senexis using `dev-master` as the composer version doesn't work as a workaround, it's still throw `Call to undefined method Whitecube\NovaFlexibleContent\Layouts\Layout::forceFill()`. Am I missing something?

**Comment by toonvandenbos** [comment]
Released in v1.0.12. Thank you for your help everyone!
