### ISSUE TITLE
`Unable to parse incoming Flexible content` error after update to v0.1.8

### ISSUE THREAD

**Issue by gwleuverink** [whitecube/nova-flexible-content#53]
Hi all, Thanks so much for this great package! 
I updated to v0.1.8 yesterday and ran into some trouble with presets.

I have the following in  `TwoColumns.php`

``` php 
public function fields()
{
    return [
        Flexible::make('Left column')
            ->preset(\App\Nova\Flexible\Presets\TwoColumnsPreset::class),

        Flexible::make('Right column')
            ->preset(\App\Nova\Flexible\Presets\TwoColumnsPreset::class),
    ];
}
```

Both of those columns use a preset. In this case `TwoColumnsPreset.php`

``` php 
public function handle(Flexible $field)
{
    $field->hideFromIndex()
        ->addLayout(\App\Nova\Flexible\Layouts\TextSection::class)
        ->addLayout(\App\Nova\Flexible\Layouts\BulletList::class)
        ->addLayout(\App\Nova\Flexible\Layouts\CheckList::class)
        ->addLayout(\App\Nova\Flexible\Layouts\VideoEmbed::class)
        // e.t.c...
}
```

In v0.1.7 this worked without any issues, but since the v0.1.8 update Nova throws an error when adding flexible fields to the first column. The peculiar thing is that adding layouts to the second works as expected.

When trying to store data in the left column Nova throws an exeption with the message `Unable to parse incoming Flexible content, data should be an array.`. Below I've posted part of the trace:

![Screen Shot 2019-08-13 at 09 28 59](https://user-images.githubusercontent.com/17123491/62922966-f8efcb00-bdac-11e9-83e2-8118113d1310.png)

It doesn't matter what type of presets are added to a layout. If I remove all inputs other than a textfield for example this error still occurs.

Is this a bug or am I doing something wrong? Hope you can reproduce and help me out :)

Thanks!

**Comment by Nyratas** [comment]
Hi @gwleuverink,

Could you post a sample of the data stored for the first field (if it already has content, of course)?

Also, what is `TwoColumns`? A simple "model" resource?

Could you open the package's vendor files and try the following:

1. Open `Whitecube\NovaFlexibleContent\Http\Middleware\InterceptFlexibleAttributes` ;
2. Add `info($request->input('left_column'));` at line `29` (right after `$request->request->remove(FlexibleAttribute::REGISTER);`) ;
3. Fill the Flexible field with some test data then run the error again by submitting the Nova form ;
4. Open the log file and post the result from the `info()` call here.

Thanks!

**Comment by gwleuverink** [comment]
Hi @Nyratas, Thanks for getting back to me so quickly.

Sorry about the confusion. `TwoColumns.php` is a Flexible layout class. 

I have a `Page` resource which stores flexible content inside a `content` json column. The flexible field that stores to this column uses multiple layouts, of which `TwoColumns` is one.

The `TwoColumns` Layout in it's turn has two flexible fields, one for each column. Each of these fields uses a preset with flexible fields.

It's a little confusing reading it like this. Please tell me if and how I can make it more understandable :)

Below is the result from the log you requested. I also tried dumping the value. It seems like `$request->input('left_column')` is null. 
```
[2019-08-13 12:20:38] local.INFO:   
[2019-08-13 12:20:38] local.ERROR: Unable to parse incoming Flexible content, data should be an array. {"userId":1,"exception":"[object] (Exception(code: 0): Unable to parse incoming Flexible content, data should be an array. at /home/vagrant/code/mapstell/vendor/whitecube/nova-flexible-content/src/Flexible.php:268)
[stacktrace]
#0 /home/vagrant/code/mapstell/vendor/whitecube/nova-flexible-content/src/Flexible.php(381): Whitecube\\NovaFlexibleContent\\Flexible->extractValue(Object(Whitecube\\NovaFlexibleContent\\Http\\ScopedRequest), 'left_column')
#1 /home/vagrant/code/mapstell/vendor/whitecube/nova-flexible-content/src/Flexible.php(354): Whitecube\\NovaFlexibleContent\\Flexible->getFlexibleRules(Object(Whitecube\\NovaFlexibleContent\\Http\\ScopedRequest), 'creation')
#2 [internal function]: Whitecube\\NovaFlexibleContent\\Flexible->getCreationRules(Object(Whitecube\\NovaFlexibleContent\\Http\\ScopedRequest))
#3 /home/vagrant/code/mapstell/vendor/whitecube/nova-flexible-content/src/Layouts/Layout.php(272): call_user_func(Array, Object(Whitecube\\NovaFlexibleContent\\Http\\ScopedRequest))


// Omitted the rest of the trace since it's the same as shown in the screenshot in my first comment
```

Since the parent flexible field stores to the `content` attribute I also dumped that, this might provide some more info.

```
[2019-08-13 12:40:29] local.INFO: array (
  0 => 
  array (
    'layout' => 'two-columns',
    'key' => 'glg6adqucd878ueerct96j-two-columns',
    'attributes' => 
    array (
      'left_column' => '[{"layout":"text-section","key":"ahsm1ml0qn50ry8jy96p7l-text-section","attributes":{"ahsm1ml0qn50ry8jy96p7l-text-section__title":"Foo","ahsm1ml0qn50ry8jy96p7l-text-section__content":"<div>Bar</div>","ahsm1ml0qn50ry8jy96p7l-text-section__contentDraftId":"6d54d51e-1bcc-4a98-9ee1-09331b808505","ahsm1ml0qn50ry8jy96p7l-text-section__centered":"0"}}]',
      'right_column' => 
      array (
        0 => 
        array (
          'layout' => 'text-section',
          'key' => '3ogeoic4i0lrtoey9yz8s-text-section',
          'attributes' => 
          array (
            'title' => 'Baz',
            'content' => '<div>Foo</div>',
            'contentDraftId' => '7ba63a53-7e5b-4c2f-b549-4318b1993885',
            'centered' => '0',
          ),
        ),
      ),
    ),
  ),
)  
```

It looks like the `left_column` isn't deserialised. The problem occurs when creating and also when updating.

I can confirm that this works when I downgrade back to 0.1.7. 

Thanks again!

**Comment by Nyratas** [comment]
Alright, thanks for the feedback! 

I think I know where the issue comes from. I'll keep you updated.

**Comment by gwleuverink** [comment]
Awesome!

**Comment by Nyratas** [comment]
I published a potential fix with a087553. Could you try it out (using `dev-master`) and tell me if it fixes your issue?

**Comment by gwleuverink** [comment]
Just tried it out but it doesn't seem to fix the issue. `$this->requestHasParsableFlexibleInputs($request)` now returns a false negative

**Comment by Nyratas** [comment]
Did you reload the page without cache before submitting the form? There were some changes in the vue files too.

**Comment by gwleuverink** [comment]
Rookie mistake that fixed it! Thanks a lot! I have to say support on this repo is top notch. Keep it up!

**Comment by Nyratas** [comment]
Nice! Thanks for the kind words :)

The fix has been released in v0.1.9, I'd suggest to remove `dev-master` from your composer.json file since it could break things again with our next draft releases.

Have a nice day!

**Comment by Bessamu** [comment]
Hi. I have similar problem.

`Unable to parse incoming Flexible content, data should be an array.`

![image](https://user-images.githubusercontent.com/36696244/62943080-56ead580-bde2-11e9-8b39-1e9b5c1e0c32.png)

I updated to 0.1.9 but problem not resolved for me.

My resource have this Flexible field
```php
Flexible::make('Содержание новости', 'body_json')
    ->addLayout('Блок с текстом', 'wysiwyg', [
        Text::make('Заголовок', 'title'),
        NovaTrumbowyg::make('Содержание', 'body')
    ])
    ->addLayout('Youtube видео', 'video', [
        Text::make('Заголовок', 'title'),
        Image::make('Video Thumbnail', 'thumbnail'),
        Text::make('ID видео (YouTube)', 'video'),
        Text::make('Примечание к видео', 'desc')
    ])
    ->button('Добавить блок')
```

**Comment by gwleuverink** [comment]
@Bessamu Did you flush the browser cache?

**Comment by Bessamu** [comment]
@gwleuverink Yes. Wrote more informative [here](https://github.com/whitecube/nova-flexible-content/issues/54)
